#pragma once
#include "stdafx.h"


class VirtualWifiErrorMes
{
public:
	static CONST_STR KEY_TOO_SHORT;
	static CONST_STR NOT_FIND_NET;
    static CONST_STR ERROR_MES_START_WIFI_FAIL;
	static CONST_STR ERROR_MES_STOP_WIFI_FAIL;
	static CONST_STR FILE_PARSE_ERROR;
	static CONST_STR NET_NOT_CONNECTED;
	static CONST_STR NOT_FIND_VIRTUALADAPTER;
	static CONST_STR NOT_FIND_CONNECTD_ADAPTER;
	static CONST_STR NOT_FIND_NET_ADAPTER;
	static CONST_STR SET_SHARE_ADAPTER_ERROR;
	static CONST_STR SET_IP_DNS_FAIL;
	static CONST_STR GET_ADAPTER_INFO_ERROR;
	static CONST_STR OPEN_REG_FAIL;
	static CONST_STR IS_NOT_SUPPORT_WIFI;

	static CONST_STR BALLON_SHOW_FAIL;
public:
	//∆Ù∂Ø ß∞‹‘≠“Ú
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_UNSPECIFIED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_BAD_PARAMETERS;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_SERVICE_SHUTTING_DOWN;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_INSUFFICIENT_RESOURCES;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_ELEVATION_REQUIRED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_READ_ONLY;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_PERSISTENCE_FAILED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_CRYPT_ERROR;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_IMPERSONATION;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_STOP_BEFORE_START;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_INTERFACE_AVAILABLE;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_INTERFACE_UNAVAILABLE;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_MINIPORT_STOPPED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_MINIPORT_STARTED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_INCOMPATIBLE_CONNECTION_STARTED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_INCOMPATIBLE_CONNECTION_STOPPED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_USER_ACTION;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_CLIENT_ABORT;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_AP_START_FAILED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_PEER_ARRIVED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_PEER_DEPARTED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_PEER_TIMEOUT;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_GP_DENIED;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_DEVICE_CHANGE;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_PROPERTIES_CHANGE;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_VIRTUAL_STATION_BLOCKING_USE;
	static CONST_STR WLAN_HOSTED_NETWORK_REASON_SERVICE_AVAILABLE_ON_VIRTUAL_STATION;
};

