#include "stdafx.h"

class VirtualWifiConst
{
public:
	static CONST_STR MAIN_SOCKET_ID;
	static CONST_STR CONFIG_SOCKET_ID;
	static CONST_STR FLOW_MONITOR_ID;
	static CONST_STR LOCAL_IP;

	static CONST_STR CONST_SZ_FRIST_START_APP;
	static CONST_STR CONST_SZ_START_WIFI_SUCCESS;
	static CONST_STR ALREADY_STARTED;
	static CONST_STR CONST_SZ_STOP_WIFI_SUCCESS;

	static CONST_STR AUTO_START_WIFI_PARAMETERS;

	static CONST_STR HAS_NEW_CLIENT_LINK;
};